"""Change CategoryName.budget_type_id

Revision ID: 20e005582a88
Revises: 7bd257900cc4
Create Date: 2022-10-21 17:58:03.761555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e005582a88'
down_revision = '7bd257900cc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_name', sa.Column('budget_type_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_category_name_budget_type_id'), 'category_name', ['budget_type_id'], unique=False)
    op.create_foreign_key(None, 'category_name', 'budget_type', ['budget_type_id'], ['id'])
    op.drop_column('category_name', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_name', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category_name', type_='foreignkey')
    op.drop_index(op.f('ix_category_name_budget_type_id'), table_name='category_name')
    op.drop_column('category_name', 'budget_type_id')
    # ### end Alembic commands ###
