"""Delete model budget

Revision ID: 36931166c6cd
Revises: 88971773dae3
Create Date: 2022-11-02 22:01:40.920900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36931166c6cd'
down_revision = '88971773dae3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_budget_budget_type_id', table_name='budget')
    op.drop_table('budget')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('budget_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['budget_type_id'], ['budget_type.id'], name='budget_budget_type_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='budget_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='budget_pkey')
    )
    op.create_index('ix_budget_budget_type_id', 'budget', ['budget_type_id'], unique=False)
    # ### end Alembic commands ###
